# Generated by Django 5.1.1 on 2024-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("updated_dt", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("content", models.TextField(blank=True)),
                (
                    "weather",
                    models.CharField(
                        choices=[("sunny", "맑음"), ("cloudy", "구름"), ("rainy", "비"), ("snowy", "눈")], max_length=10
                    ),
                ),
            ],
            options={
                "db_table": "diary",
            },
        ),
    ]
