# Generated by Django 5.1.1 on 2024-09-27 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name="diary",
            index=models.Index(fields=["user", "date", "id"], name="diary_user_id_aa1045_idx"),
        ),
        migrations.AddConstraint(
            model_name="diary",
            constraint=models.UniqueConstraint(fields=("user", "date"), name="unique_user_date_diary"),
        ),
    ]
