# Generated by Django 5.1 on 2024-09-11 15:53

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(choices=[('sunny', '맑음'), ('cloudy', '구름'), ('rainy', '비'), ('snowy', '눈')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='diary',
            index=models.Index(fields=['user', 'date'], name='diary_user_id_b99d8f_idx'),
        ),
    ]
