# Generated by Django 5.1.1 on 2024-09-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="diary",
            name="unique_user_date_diary",
        ),
    ]
