# Generated by Django 5.1.1 on 2024-09-28 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_remove_diary_unique_user_date_diary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="diary",
            constraint=models.UniqueConstraint(fields=("user", "date"), name="unique_user_date_diary"),
        ),
    ]
