# Generated by Django 5.1.1 on 2024-09-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_diary_unique_user_date_diary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="date",
            field=models.DateField(),
        ),
    ]
