# Generated by Django 5.1 on 2024-08-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diary_date'),
        ('tag', '0002_alter_tag_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='diary.diary'),
        ),
    ]
